# config.yaml - Конфигурация анализа PDF
tolerance_mm: 5.0  # Допуск для распознавания форматов (мм)
compress_ranges: 1  # Сжимать диапазоны 1-да, 0-нет.

formats:
  A0: [841, 1189]
  "A0×2": [1189, 1682]
  "A0×3": [1189, 2523]
  A1: [594, 841]
  "A1×3": [841, 1783]
  "A1×4": [841, 2378]
  A2: [420, 594]
  "A2×3": [594, 1261]
  "A2×4": [594, 1682]
  "A2×5": [594, 2102]
  A3: [297, 420]
  "A3×3": [420, 891]
  "A3×4": [420, 1189]
  "A3×5": [420, 1486]
  "A3×6": [420, 1783]
  "A3×7": [420, 2080]
  A4: [210, 297]
  "A4×3": [297, 630]
  "A4×4": [297, 841]
  "A4×5": [297, 1051]
  "A4×6": [297, 1261]
  "A4×7": [297, 1471]
  "A4×8": [297, 1682]
  "A4×9": [297, 1892]
